# -*- coding: utf-8 -*-
"""Week03_LoadingDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diPptwbYAN9h0A-UZLfvzBhRx4aopcGZ
"""

from torch.utils.data import Dataset
from sklearn.datasets import fetch_openml

#Loads data from
#https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
print(X.shape)

class SimpleDataset(Dataset):

  def __init__(self, X, y):
    super(SimpleDataset, self).__init__()
    self.X = X.to_numpy()
    self.y = y

  def __getitem__(self, index):
    inputs = torch.tensor(self.X[index,:], dtype=torch.float32)
    targets = torch.tensor(int(self.y.iloc[index]), dtype=torch.int64)
    return inputs, targets

  def __len__(self):
    return self.X.shape[0]

dataset = SimpleDataset(X, y)

import torch
print("Length: ", len(dataset))
example, label = dataset[0]
print("Features: ", example.shape) #Returns 784
print("Label of index 0: ", label)
#print(example)

import matplotlib.pyplot as plt
plt.imshow(example.reshape((28,28)))

train_size = int(len(dataset)*0.8)
test_size = len(dataset)-train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset,\
(train_size, test_size))
print("{} examples for training and {} for testing".format\
(len(train_dataset), len(test_dataset)))


#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================
#=========================================================

# -*- coding: utf-8 -*-
"""Week03_LoadingDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diPptwbYAN9h0A-UZLfvzBhRx4aopcGZ
"""

# Import necessary modules
from torch.utils.data import Dataset
from sklearn.datasets import fetch_openml
import torch
import matplotlib.pyplot as plt

# --- 1. LOAD RAW DATA ---
# Loads the MNIST dataset (handwritten digits) from OpenML.
# https://www.openml.org/d/554
# return_X_y=True gives us the features (X) and labels (y) directly.
# X will be a pandas DataFrame of shape (70000, 784).
# y will be a pandas Series of shape (70000,).
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
print(f"Data Shape: {X.shape}")

# --- 2. DEFINE CUSTOM DATASET CLASS ---
# A custom Dataset class must inherit from torch.utils.data.Dataset
# and implement __len__ and __getitem__.
class SimpleDataset(Dataset):

  def __init__(self, X, y):
    super(SimpleDataset, self).__init__()
    # Convert features to a NumPy array for easier indexing.
    # Storing data in self allows it to be accessed by other methods.
    self.X = X.to_numpy()
    self.y = y

  def __getitem__(self, index):
    # This method retrieves the i-th sample from the dataset.
    # It allows the dataset to be indexed like a list (e.g., dataset[0]).
    
    # 1. Get features: Convert row 'index' to a Float32 Tensor.
    # float32 is the standard type for input data in PyTorch neural networks.
    inputs = torch.tensor(self.X[index,:], dtype=torch.float32)
    
    # 2. Get label: Use .iloc because 'y' is still a pandas Series.
    # Convert to int64 (Long) Tensor, which is required for classification labels.
    targets = torch.tensor(int(self.y.iloc[index]), dtype=torch.int64)
    
    return inputs, targets

  def __len__(self):
    # Returns the total number of samples. 
    # Used by DataLoader to know when an epoch ends.
    return self.X.shape[0]

# Instantiate the dataset object
dataset = SimpleDataset(X, y)

# --- 3. INSPECT DATA ---
print("Length: ", len(dataset))

# Get the first sample (feature vector and label)
example, label = dataset[0]
print("Features: ", example.shape) # Returns torch.Size([784]) representing 28x28 flattened pixels
print("Label of index 0: ", label) # Returns the digit label (e.g., 5)

# --- 4. VISUALIZATION ---
# The data is flattened (1D vector of 784 pixels).
# To visualize it as an image, we must reshape it back to 2D (28x28).
plt.imshow(example.reshape((28,28)))
plt.show() # Display the plot

# --- 5. CREATE TRAIN/TEST SPLIT ---
# Calculate sizes: 80% for training, 20% for testing.
train_size = int(len(dataset)*0.8)
test_size = len(dataset)-train_size

# random_split randomly divides the dataset into non-overlapping new datasets.
train_dataset, test_dataset = torch.utils.data.random_split(dataset, (train_size, test_size))

print("{} examples for training and {} for testing".format(len(train_dataset), len(test_dataset)))