# -*- coding: utf-8 -*-
"""Week03_LoadingDataset_Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qIWAQbg1702qzZjBjK0zXCDgV-qzFDp
"""

import torch
from torch.utils.data import Dataset
from sklearn.datasets import load_svmlight_file
import pandas as pd

# Given SimpleDataset class
class SimpleDataset(Dataset):
    def __init__(self, X, y):
        super(SimpleDataset, self).__init__()
        self.X = X.to_numpy()
        self.y = y

    def __getitem__(self, index):
        inputs = torch.tensor(self.X[index, :], dtype=torch.float32)
        targets = torch.tensor(int(self.y.iloc[index]), dtype=torch.int64)
        return inputs, targets

    def __len__(self):
        return self.X.shape[0]


def libsvm2Dataset(filepath, expected_num_features=None):
    """
    Reads a LIBSVM formatted dataset and converts it to a SimpleDataset.

    Args:
        filepath (str): Path to the LIBSVM file.
        expected_num_features (int): Optional, the expected number of features per row.

    Returns:
        dataset (SimpleDataset): The dataset created from the LIBSVM file.
    """
    # Step 1: Read the data using load_svmlight_file (converts it to a sparse matrix)
    X_sparse, y = load_svmlight_file(filepath)

    # Step 2: Convert to dense matrix (DataFrame) for easier manipulation
    X = pd.DataFrame(X_sparse.toarray())  # Convert to dense format for ease of use
    y = pd.Series(y)  # Convert to Pandas Series

    """
    # Step 3: Check if the length of the dataset is correct
    if len(X) != len(y):
        raise ValueError("The number of feature rows does not match the number of labels.")

    # Step 4: Check if the number of features per row matches the expected number of features
    if expected_num_features is not None and X.shape[1] != expected_num_features:
        raise ValueError(f"Each row should have {expected_num_features} features, but got {X.shape[1]}.")
    """
    # Step 5: Create and return the SimpleDataset object
    dataset = SimpleDataset(X, y)

    return dataset

# Assuming the file 'dataset.txt' is in LIBSVM format and has 100 features per row.
dataset = libsvm2Dataset('/content/drive/My Drive/Colab Notebooks/Week03/a1a.txt', expected_num_features=119)

# Check dataset length
print(f"Dataset length: {len(dataset)}")

# Access a data point
inputs, label = dataset[0]
print("Features: ", inputs.shape)
print("Label of index 0: ", label)
print(inputs, label)

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/My Drive/Colab Notebooks/Week03/a1a.txt', 'r') as f:
    text = f.read()
print(text)